# /// script
# dependencies = [
#   "django-bolt[nanodjango]",
# ]
# ///
"""
Minimal django-bolt + nanodjango single-file example.

Run via nanodjango's CLI:
    nanodjango manage examples/nanodjango/helloworld.py runbolt --port 8000

or

run with automatic dependency downloads and virtenv creation:
    uv run examples/nanodjango/helloworld.py runbolt --port 8000

"""

from __future__ import annotations

import sys
import asyncio
from html import escape
from nanodjango import Django
from django_bolt.nanodjango import BoltAPI
from django_bolt.responses import StreamingResponse
from django_bolt.middleware import no_compress

app = Django()
bolt = BoltAPI()

#  <a href="/api/hello">hello</a> or  <a href="/api/greet?name=World">greet?name=World</a> or <a href="/api/stream">stream 5 responses</a>
@app.route("/")
def home(request):
    return r"""<title>helloworld: django-bolt+nanodjango</title>
    <h1>Hello, single file apps with Django-Bolt and nanodjango</h1>
    This page is a django view, served by the bolt/Actix server. The links below introduce bolt's API calls which return json responses.<br/>
<nav aria-label="Api Navigation">
  <ul>
    <li><a href="/api/hello">/api/Hello</a> - say hello</li>
    <li><a href="/api/greet?name=World">/api/greet?name=World</a> - return greeting with name=World as argument</li>
    <li><a href="/api/stream">/api/stream</a> return 5 responses separated by 1 second</a>
  </ul>
</nav>
    <p>Check out the autogenerated <a href="/docs/">API docs</a>.</p>

    <details>
    <summary>Source Code</summary>
    <pre>%s</pre></details>
    """ % escape(open(__file__).read())


@bolt.get("/api/hello")
async def hello(request):
    return {"message": "hello from bolt"}


@bolt.get("/api/greet")
async def greet(name: str):
    return {"message": f"hello, {name}!"}


@bolt.get("/api/stream")
@no_compress # don't compress streaming responses - would batch them together
async def stream(request)-> StreamingResponse:
    """send 5 messages, one every second, then end the stream"""
    async def generate():
        for i in range(5):
            yield f"data: message {i} asyncio.sleep(1)\n\n".encode()
            await asyncio.sleep(1)

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
    )



# Register catch-all AFTER all bolt routes so they take priority.
# Unmatched requests (like /) are forwarded to Django's ASGI app.
bolt.mount_django(r"/")


if __name__ == "__main__":
    from django.core.management import execute_from_command_line  # noqa: E402

    execute_from_command_line(sys.argv)
